namespace KitchenPC
{
   public enum UnitType
   {
      Unit = 0,
      Volume = 1,
      Weight = 2
   }

   public enum Units
   {
      //Individual items
      Unit = 0,

      //Volume
      Teaspoon = 1,
      Tablespoon = 2,
      FluidOunce = 3,
      Cup = 4,
      Pint = 5,
      Quart = 6,
      Gallon = 7,

      //Weight
      Gram = 8,
      Ounce = 9,
      Pound = 10,
      
      // new units
      G = 11,
      kg = 12,
      Lb = 13,
      Lbs = 14,
      Pounds = 15,
      Oz = 16,
      Ozs = 17,
      Cups = 18,
      Ml = 19,
      Rip = 20,
      L = 21,
      Liter = 22,
      Liters = 23,
      Tsp = 24,
      Tsps = 25,
      Tbsp = 26,
      Tbsps = 27,
      Qt = 28,
      Bunch = 29,
      Scoop = 30,
      Scoops = 31,
      Leaf = 32,
      Leaves = 33,
      Drop = 34,
      Drops = 35,
      Sheet = 36,
      Sheets = 37,
      Slice = 38,
      Slices = 39,
      Inch = 40,
      Inches = 41,
      Stalk = 42,
      Stalks = 43,
      Stick = 44,
      Sticks = 45,
      Strip = 46,
      Strips = 47,
      Sprig = 48,
      Sprigs = 49,
      Dash = 50,
      Dashes = 51,
      Pinch = 52,
      Pinches = 53,
      Best = 54,
      David = 55,
      Can = 56,
      Cans  = 57,
      Ounces  = 58,
      Cloves  = 59,
      Handful  = 60,
      Ribs  = 61,
      Small  = 62,
      Medium  = 63,
      Large  = 64,
      Head  = 65,
      Heads  = 66,
      Link  = 67,
      Links  = 68,
      Piece  = 69, 
      Pieces  = 70,
      Whole  = 71,
      Teaspoons  = 72,
      Tablespoons  = 73,
      FluidOunces  = 74,
      Pints  = 75,
      Quarts  = 76,
      Gallons  = 77, 
      Grams  = 78,
   }
}